spring:
  cloud:
    gateway:
      routes:
        - id: product-microservice
          uri: lb://product-microservice
          predicates:
            - Path=/api/product-microservice/**
#            - Header= token, \d+
#            - Header= Content-Type, application/json
#            - Method= GET, POST #PUT, DELETE
#            - Query= color
#            - Cookie= color, azul
          filters:
            - StripPrefix=2
            - PersonalizedCookie=Hola mi mensaje personalizado, usuario, juanchoio
#            - name: Personalized
#              args:
#                mensaje: Hola mi mensaje personalizado
#                cookieName: usuario
#                cookieValor: juanchoio
        - id: item-microservice
          uri: lb://item-microservice
          predicates:
            - Path=/api/item-microservice/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - AddRequestParameter=nombre, juan
            - SetResponseHeader=Content-Type, text/plain