resilience4j:
  circuitbreaker:
    configs:
      defaultConfig:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: defaultConfig
  timelimiter:
    configs:
      defaultConfig:
        timeout-duration: 2s
    instances:
      products:
        base-config: defaultConfig
spring:
  cloud:
    gateway:
      routes:
        - id: product-microservice
          uri: lb://product-microservice
          predicates:
            - Path=/api/product-microservice/**
#            - Header= token, \d+
#            - Header= Content-Type, application/json
#            - Method= GET, POST #PUT, DELETE
#            - Query= color
#            - Cookie= color, azul
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCodes: 500
                fallbackUri: forward:/api/item-microservice/items/annotation2/9/quantity/5
            - StripPrefix=2
            - PersonalizedCookie=Hola mi mensaje personalizado, usuario, juanchoio
#            - name: Personalized
#              args:
#                mensaje: Hola mi mensaje personalizado
#                cookieName: usuario
#                cookieValor: juanchoio
        - id: item-microservice
          uri: lb://item-microservice
          predicates:
            - Path=/api/item-microservice/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - AddRequestParameter=nombre, juan
            - SetResponseHeader=Content-Type, text/plain